version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ./containers/nginx/Dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
      volumes:
          - ./code:/tmp
  php:
      build:
        context: .
        dockerfile: ./containers/php/Dockerfile
      ports:
          - "8000:80"
